### PR TITLE
Modaal demo hosted on GitHub Pages

### PR DESCRIPTION
**Pull request by pzi**
Hi Humaans,

After the Port80 meetup last Wednesday and a discussion with @cbotman, I decided to spend some time and convert your demo page from PHP to Jekyll/Liquid. This means, the demo can be [hosted on GitHub Pages](https://help.github.com/articles/about-github-pages-and-jekyll/). This may make the deployment process simpler (more of that below).

#### Demo

The code in this PR is currently running on a GitHub Page on my account:
- [`gh-pages` branch](https://github.com/pzi/Modaal/tree/gh-pages/)
- http://patrikaffentranger.me/Modaal/

#### Changes

As you can see in the diff, I have
- made the demo folder completely self-standing.
- changed the `.php` files to `html` and `svg` respectively (no php on `gh-pages`, so no `include()` or `sleep()`).
- added a new gulp task to copy the minified source into the demo folder (`copy-to-demo`).
- added another gulp task to deploy the demo to `gh-pages` (`deploy-to-gh-pages`).
- moved each Modaal example into a partial.

What needs to happen before the demo works 100%:
- Update Google Analytics settings(?)
- Update addthis settings
- Create `modaal.humaan.com.au` subdomain that points to this repository’s `gh-pages`.

#### Caveat
Just as it was a hurdle to get the demo to work locally for someone with no Apache/PHP installed, it has now shifted to a [Ruby dependency](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/#step-2-install-jekyll-using-bundler). However, it could easily shift to just being HTML only (if you would go without requiring the Modaal logo and just inline it).
Alternatively, I can add a `Gemfile` with the necessary RubyGems to get it to run locally.

Let me know what you think. Looking forward to your feedback and a discussion about my proposed changes.

Cheers
Patrik

### CODE REVIEW

**Comment by cbotman** [comment]
Hey @pzi, sorry we haven't responded to this, was a busy week. Dan and I tried to schedule time every day to take a look, and it's now 4pm Friday...Next week! ;)

**Comment by pzi** [comment]
No worries at all. It's there for you to play with... whenever that is :) Have a nice weekend!

**Comment by cbotman** [comment]
@danhumaan One talking point from this is the demo page should probably be static HTML so people can download the repo and open it without having to run it on a (PHP enabled) web server.

**Comment by danhumaan** [comment]
@cbotman i definitely agree with that

**Comment by pzi** [comment]
Hey!

As I mentioned in my PR, my implementation is based on Jekyll/Liquid. However, this can easily be reversed/removed and everything can be static. Up to you...

Another option would be to use something like [gulp-file-include](https://www.npmjs.com/package/gulp-file-include) or [gulp-include](https://www.npmjs.com/package/gulp-include) to still get the benefit of "includes". Again, up to you how simple or complex you prefer it :)

Cheers
Patrik

**Comment by danhumaan** [comment]
@pzi thanks Patrik, appreciate the contribution! once we find some time to get back into addressing the latest activity we'll look into what we can do with this and the demo page :)

**Comment by pzi** [comment]
Hello again Humaans,

After another discussion with @cbotman at Port80 on Wednesday I moved the demo source back to plain HTML/CSS/JS. So the Jekyll/Ruby dependency is gone now.

The only thing that "stops" someone from looking at it locally now is the lack of http protocol in the vendor script links (jQuery, Google Analytics, addthis).

I also realigned my branch with what's currently in `develop`. If you prefer I squash the commits before you merge, just let me know and I will make it happen :)

Cheers
Patrik

**Comment by pzi** [comment]
Rebased my branch on develop and updated the demo files (3603bdd) in this PR.

**Comment by pzi** [comment]
Hey Humaans,

Given I have removed the Ruby dependencies and turned 2 PHP files into a HTML and a SVG file respectively, there is really not much else holding you up from making a decision of whether this PR has a future or not.

If you don't want to use `gh-pages`, there's nothing wrong with that. Just let me know and I will remove the introduced gulp task that "deploys to github" and it's good to go.

If you prefer not to go ahead with anything I proposed - although, I've seen you adopt 89038c93ed8427ad7111aff587ec8a4918330fa9 - just let me know and I can save myself some time trying to keep up with the rest of the codebase.

Cheers
Patrik

**Comment by danhumaan** [comment]
Hey Patrik,

First up thanks for your contribution here and for staying on top of it as we've been pushing out other amendments. Thanks also for your patience and my apologies it's taken us so long to get round to addressing this PR.

We've decided at this point in time not to host the page on Github pages, and during the merge I hopped in an removed the relevant gulp task. I've also made a few minor tweaks to resolve merge conflicts and to relocate the index.html file as this will live easier on our current server.

We're due to roll out a v0.3.1 version any time now (few minor things to address), so we can expect your contributes to roll out with that.

Again, thanks for your contribution and patience.

Cheers,
Dan

**Pull request merged**
