### PR TITLE
add an open method. closes #63

### LINKED ISSUE #63: Open method
"_Currently Modaal only supports a close method which can be called like so._"
Why does it only support `close` instead of supporting `open` & `close` ? _open method_ is useful when we want to trigger the modaal's open programatically

### PR DESCRIPTION
**Pull request by james2doyle**
This adds support to open the method. Similar to the close support.

For example:

```js
$('.my-link').modaal('open');
```

I tested this on the demo page, and it seems to be working nicely.

I have a linter and formatter enabled on my editor. So there are some tweaks to the formatting.

Basically, I added a new method `create_modaal` which is used by both _the element click-to-open_ and the new _pass a string to close_ option. I also added code to stop the modal from being recreated when open is called on a modal that is already open.

### CODE REVIEW

**Comment by james2doyle** [comment]
any thoughts on this?

**Comment by pzi** [comment]
> @james2doyle: any thoughts on this?

Personally, I feel that you should revert the changes your linter has made given that is a matter of personal preference and has nothing to do with the added functionality. Ultimately, it's up to the maintainer/project owner, though.

**Comment by danhumaan** [comment]
hi @james2doyle thanks for your contribution. It looks good and i'd like to do some testing on it to see how it all goes. Finding the time is a bit of a challenge at the moment so please bear with me while we balance the schedules.

With that said, I tend to agree with @pzi's comment, which I tend to agree with. There are a handful of committed updates that appear to be personal preferences or automated updates based on a linter. Granted there are some things that are highlighted as requiring attention (differences in indentation for example), but I would ask that you update your pull request so the changes recommended focus only on the new open method.

Cheers,
Dan

**Comment by james2doyle** [comment]
I see what you mean. I can submit another PR but I am not sure when I will get around to it.

**Comment by danhumaan** [comment]
No worries @james2doyle - the other differences aren't going to stop us from doing some testing, so if you haven't submitted anything by then it's no trouble. If we're happy with how the new stuff is going we'll find a way to include it and address the other differences then.

Thanks again, looking forward to testing it soon.

**Comment by james2doyle** [comment]
Yeah, that works then. We already have this working on a site in
production. We needed this feature so that we could open a specific modal
on page load depending on a URL hash.

**Comment by danhumaan** [comment]
Thank you, this PR has been used as the basis for this implementation. Due to some other larger updates to the Modaal.js we've worked through this manually.

I'm going to close this PR but please keep an eye out for the next release for this implementation. 

Cheers,
Dan

**Pull request closed without merging**
