### PR TITLE
Makes video types correctly centered

### PR DESCRIPTION
**Pull request by Ruxton**
Adds auto margin-left and right for video containers.  GIFs below show the change.

Current Live Demo:
modaal-video-current

Change:
modaal-video-fix

### CODE REVIEW

**Comment by danhumaan** [comment]
Hi @Ruxton, This appears to be performing correctly for us without the change you're proposing.
Are you able to please supply the browser, operating system and screen dimensions so we can investigate further?

**Comment by pzi** [comment]
Happens for me as well, but only when viewport width is between ~1020px and 1400px width

screen shot 2016-04-28 at 13 38 56

Here's a gif of the chrome device mode:
modaal

**Comment by Ruxton** [comment]
OSX 10.10.5 on a Retina 15" Early 2013
Chrome 50.0.2661.86 
Firefox 44
Safari 9.1

Happens in all of these at certain widths.  Current window.innerWidth is 1256 and I'm seeing the issue, is fine at 1440px

**Comment by danhumaan** [comment]
Thanks @Ruxton and @pzi  - we'll check it out.

**Comment by danhumaan** [comment]
Hi @Ruxton, thanks again. Because we have a few other changes waiting to be released, I've completed the same changes you had amongst a few others and committed them to the develop branch until we push out a new release.

Will update this once a new release is available.

**Comment by Ruxton** [comment]
:+1

**Comment by cbotman** [comment]
This should now be live. :) Thanks again everyone.

**Pull request closed without merging**
