### PR TITLE
sort CSS properties alphabetically

### PR DESCRIPTION
**Pull request by marcobiedermann**
Sorting CSS properties alphabetically is easier to read and might be better in GZIP compression

### CODE REVIEW

**Comment by deviodigital** [comment]
:+1:

**Comment by Fequois** [comment]
Still not sure about those tabs. 😄  I guess it's up to the owners/maintainers.

**Comment by cbotman** [comment]
Hi @marcobiedermann, could you please resubmit this pull request to the 'develop' branch, and we'll merge it in? Thanks.

**Comment by michalsnik** [comment]
Hey, and what do you think about this approach instead of sorting all alphabetically:
1.extends
2. includes
3. box model related styles
4. typography related styles
5. graphic layer related styles

I think this way is much more readable and consistent.

For example:
```
.some-component {
    @extend %base-component;
    @include some-mixin();
    width: 200px;                  // Box model
    height: 100px;                 // Box model
    position: relative;             // Box model
    font-size: 12px;                // Typography
    font-weight: bold;             // Typography
    background: red;             // Graphic layer
    border: 1px solid #ccc;    // Graphic layer
}

Just throwing an idea, tell me what do you think.

**Comment by marcobiedermann** [comment]
Sorting properties alphabetically will save some bytes when using gzip compression. Also it is more easy to remember

**Comment by jsit** [comment]
Alphabetical CSS property sorting is a bad idea. If something is `position: absolute;` and has `top` and `left` attributes, `top` and `left` will be far from each other. Similarly, typography-related properties like `font-size` and `line-height` won't be close together.

Instead, properties should be grouped conceptually to be more legible, as suggested by @michalsnik. Using one of scss-lint's PropertySortOrder presets is probably a better idea: https://github.com/brigade/scss-lint/tree/master/data/property-sort-orders. I prefer the SMACSS sort order, as SMACSS is a well known and widely used Sass methodology.

**Comment by danb-humaan** [comment]
Closing now, reference #32 for further details.

**Pull request closed without merging**
