### PR TITLE
Add main attribute in order to support jspm

### PR DESCRIPTION
**Pull request by pvledoux**

### CODE REVIEW

**Comment by danhumaan** [comment]
Hi @pvledoux, thanks for submitting the pull request. We now support NPM and Bower, and it's straight forward enough we'd be happy to support jspm.. Is this all that's required to support the package manager? I'm not familiar with jspm at all.

**Comment by danb-humaan** [comment]
Anyone have any recommendations as to whether it's better off importing `modaal.min.js` or `modaal.js`?  #74 has the non-minified dist file being imported, but this PR has the minified build.

Personally, I'm _inclined_ to go with the non-minified build of Modaal as that way others can use their own minifier of choice to perform the appropriate minification etc.  

@pzi - as someone who has more experience with JavaScript modules, do you have a recommendation as to which file should be considered the default import module?

**Comment by pzi** [comment]
>Personally, I'm inclined to go with the non-minified build of Modaal as that way others can use their own minifier of choice to perform the appropriate minification etc.

+1

I'd recommend **non-minified**. It's up to the individual how they want to deliver the code in their project to the end-user and Modaal should make no assumptions in this regard.

**Comment by danb-humaan** [comment]
@pzi: thanks heaps, Patrik!  Much appreciated.

@pvledoux: thanks for the contribution.  We'll go with the non-minified build of Modaal (see @74) as the main package export.

**Pull request closed without merging**
