### PR TITLE
sort css properties alphabetically

### PR DESCRIPTION
**Pull request by marcobiedermann**
@cbotman resubmitted changes from #11 to `develop` branche

### CODE REVIEW

**Comment by jsit** [comment]
Alphabetical CSS property sorting is a bad idea. If something is `position: absolute;` and has `top` and `left` attributes, `top` and `left` will be far from each other. Similarly, typography-related properties like `font-size` and `line-height` won't be close together.

Instead, properties should be grouped conceptually to be more legible, as suggested by @michalsnik. Using one of scss-lint's PropertySortOrder presets is probably a better idea: https://github.com/brigade/scss-lint/tree/master/data/property-sort-orders. I prefer the SMACSS sort order, as SMACSS is a well known and widely used Sass methodology.

**Comment by pzi** [comment]
I'd say either way is a personal preference and ultimately up to the Humaan team/maintainer :)

**Comment by danb-humaan** [comment]
Alphabetically ordered CSS properties appears to do almost nothing to improve compression for Gzip.  In fact, the ordered CSS files were around 20-30 bytes larger than than the non-ordered files.

To make sure it wasn't just Gzip's fault, I did further tests with [Zopfli](https://github.com/google/zopfli), an improved compression algorithm over Gzip.  This resulted in a similar, but with a smaller increase in file size of around 10 bytes between the ordered file and the non-ordered file.

Interestingly, when I tested larger CSS files (files >100 KB), the ordered files were usually up to 100 bytes smaller, but that's it.  Even after 500 iterations of Zopfli, the difference is negligible.

The extra effort required to ensure the CSS rules are in alphabetical order far outweighs the benefits of data transfer saved.  If we were dealing in size difference ranges of over 500-1000 bytes then I would definitely change my tune, but at this stage I say nay.

Here's a table and graph of results from ordering the Modaal CSS, along with a few other projects we've worked on recently:

zopfli-vs-gzip

**Comment by danb-humaan** [comment]
I don't mind the idea of using a linter to format the code, but it's certainly at the bottom end of our priorities list at this stage.  Very much a nice to have.

We'll close this off for now, and maybe look at implementing the SCSS linter down the track.

**Pull request closed without merging**
