### PR TITLE
fix indentation

### PR DESCRIPTION
**Pull request by marcobiedermann**
* translate spaces to tabs
* remove trailing whitespace
* add `.editorconfig`

### CODE REVIEW

**Comment by Fequois** [comment]
Why translate spaces to tabs? This seems to be uncommon practice on web projects these days. Otherwise I agree with the changes.

**Comment by marcobiedermann** [comment]
@Fequois It does not matter if you choose tabs or spaces. The key is that you choose one of them.
Currently this project uses a mix of both.
Using different indentation will be harder to read and also causes some unexpected changes when using `git diff`

**Comment by Fequois** [comment]
@marcobiedermann Oh, definitely—I completely agree. It doesn't answer the question though, however, as I mentioned in the other PR it's ultimately up to the maintainers. 😃

**Comment by juanbrujo** [comment]
I agree that _at least_ for readability `indent_size = 2` should be added to an .gitignore. tabs / spaces is more a subjective decision IMHO.

**Comment by cbotman** [comment]
Thanks for taking the time to flag this. We'll have a chat this week, settle on what format to use (we've been migrating from tabs to spaces at Humaan, which is why we get the odd mixup like this), and tidy up the project in line with it.

**Comment by cbotman** [comment]
Hey @marcobiedermann, thanks again for this. I've merged your changes in, however we created a 'develop' branch after you made the pull request, where we're staging changes for the next release, so I merged your branch into 'develop' instead of master. Closing this now. :)

**Pull request closed without merging**
